# Generated by Django 4.2.6 on 2023-10-20 18:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maker',
            name='logo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BinaryField(), null=True, size=None),
        ),
    ]
