# Generated by Django 4.2.6 on 2023-10-23 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrecord',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 7, 54, 32, 695156), editable=False),
        ),
        migrations.AlterField(
            model_name='carrecord',
            name='vin',
            field=models.CharField(db_column='vin', max_length=17, unique=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 7, 54, 32, 697155)),
        ),
        migrations.AlterField(
            model_name='dealreview',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 7, 54, 32, 696155), editable=False),
        ),
        migrations.AlterField(
            model_name='feature',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 7, 54, 32, 698155), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 7, 54, 32, 699155), editable=False),
        ),
    ]
