# Generated by Django 4.2.6 on 2023-10-20 18:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_maker_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='volume_engine',
            new_name='max_speed',
        ),
        migrations.AlterField(
            model_name='maker',
            name='logo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BinaryField(), blank=True, null=True, size=None),
        ),
    ]
