# Generated by Django 4.2.6 on 2023-10-23 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_carrecord_created_at_alter_carrecord_vin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrecord',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 7, 58, 58, 331258), editable=False),
        ),
        migrations.AlterField(
            model_name='carrecord',
            name='vin',
            field=models.CharField(db_column='vin', max_length=17),
        ),
        migrations.AlterField(
            model_name='deal',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 7, 58, 58, 332257)),
        ),
        migrations.AlterField(
            model_name='dealreview',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 7, 58, 58, 332257), editable=False),
        ),
        migrations.AlterField(
            model_name='feature',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 7, 58, 58, 333842), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 7, 58, 58, 335415), editable=False),
        ),
    ]
